### ISSUE TITLE
Better report format

### ISSUE THREAD

**Issue by zapion** [Mozilla-TWQA/MTBF-Driver#3]
MTBF needs a readable report generated automatically.

**Comment by zapion** [comment]
@ShakoHo , it is sorts of related your work and you might be able to update here.

**Comment by ShakoHo** [comment]
Currently I create a job in jenkins called "Send MTBF Summary Report"
It will send the report every day, and collect all runs for last 7 days.
The report now will look like the attachment:

![screenshot from 2015-03-16 11 07 21](https://cloud.githubusercontent.com/assets/10972262/6660072/ac56295a-cbcc-11e4-8e02-b03eef8cdf3e.png)
